# -*- coding: utf-8 -*-
"""python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wBlJHuYXkhWNlLulgKHo1VR3ZXez6DlM
"""

print("hello,gitam")

print("hello,gitam")
print("Hyderabad")

print("hello,gitam","|||")
print("Hyderabad","|||")

print("Dedeepya,221810308019")

a = 100;
s1 = "python"
s2 = 'p'
f1 = 10.2
print(a,s1,s2,f1)
print(type(a),type(s1),type(s2),type(f1))

s1 = "100"
print(type(s1))
a = int(s1)
print(type(a))
f = 1.5

# A number is given 1234 -
# Digit count
a1 = 1234
print(len(str(a1)))

# Reading a value 
input("Message")--string

s1 = input("enter your name")
print(s1)
print(type(s1))

# want a number as a input
n1 = int(input("enter a number"))
print(n1,type(n1))

n1 = 1234
print(n1+10)
print(n1-10)
print(n1*10)
print(n1/10)  
print(n1%10)
print(n1//10)
print(n1**10)

### precedence of arth operations
-paranthesis
-power
-multiplication
-addition

x = 1+2**3/4+5
print(x)

x = 1+2**3/4*5
print(x)

### Relational Operation
- ==
- !=
- Greater(>)
- Less than(<)
- Less than or equals to(<=)
- Greater than or equal to(>=)

x = 10
a1 = x>15
print(a1)

i = 100
a1 = (i>15)and(i<800)
a2 = (i>15)and(i>800)
print(a1)
print(a2)

### control flow statements
-condition
-looping statement
**system**
syntax
if boolean expression
statements
else 
statements

# to check given number is even or odd
n = int(input("enter a number"))
if n%2==0:
   print("even")
else:
   print("odd")

# to check given number is perfectly multiple of 3 or 5 or not
n = int(input("enter a number"))
if n%3 == 0 and n%5 == 0:
   print("is a multiple")
else:
   print("is not a multiple")

# test given number is positive,negative or Zero
n = int(input("enter a number"))
if n==0:
   print("Zero")
elif n>0:
   print("positive number")
elif n<0:
   print("negative number")

